#pragma once

// Ed25519 signature verification for OTA-received firmware images.
//
// Backend is libsodium's crypto_sign_ed25519_verify_detached, not mbedTLS:
// pioarduino's prebuilt mbedTLS omits the Everest Ed25519 module. libsodium is
// always present in framework-arduinoespressif32-libs and links cleanly. The
// SHA-256 streaming hash uses mbedTLS (available, clean init/update/finish).
//
// The lamp's ~280 KB heap can't buffer a 1.4 MB image for PureEdDSA
// verify_detached, so the signing tool signs the 32-byte SHA-256 digest of the
// signed region and this path streams that region through mbedtls SHA-256 in
// 4 KB blocks, then ed25519-verifies the signature against the digest.
// Functionally hash-then-sign; the at-rest LSIG layout is unchanged.
//
// LSIG footer (96 bytes, at the tail of the signed image):
//   [0..4)   "LSIG" magic
//   [4..20)  channel, zero-padded ASCII "{type}-{channel}"
//            (e.g. "standard-stable\0", "snafu-beta\0\0\0\0\0\0")
//   [20..24) firmware version (4 LE, packed semver)
//   [24..28) signedRegionLen (4 LE, bytes covered by SHA-256)
//   [28..32) reserved (4 zero bytes)
//   [32..96) ed25519 signature (64 bytes, over the SHA-256 digest)
// The signature offset (32) is pinned: a new field comes out of the 4 reserved
// bytes or forces a protocol version bump.
//
// Public key is kFirmwarePubkey[32] in components/firmware/firmware_pubkey.h
// (generated by scripts/gen_firmware_keys.py). Channel-string matching is the
// caller's job (firmware_receiver drops cross-channel offers before accepting);
// this is the cryptographic gate, not the routing gate.

#include <cstddef>
#include <cstdint>
#include <functional>

namespace lamp { namespace firmware {

// LSIG footer byte-layout contract, shared with the build-side signing tool.
constexpr size_t kLsigFooterLen        = 96;
constexpr size_t kLsigMagicOffset      = 0;
constexpr size_t kLsigMagicLen         = 4;
constexpr size_t kLsigChannelOffset    = 4;
constexpr size_t kLsigChannelLen       = 16;
constexpr size_t kLsigVersionOffset    = 20;
constexpr size_t kLsigSignedLenOffset  = 24;
constexpr size_t kLsigReservedOffset   = 28;
constexpr size_t kLsigReservedLen      = 4;
constexpr size_t kLsigSignatureOffset  = 32;
constexpr size_t kLsigSignatureLen     = 64;

static_assert(kLsigMagicLen + kLsigChannelLen + 4 + 4 + kLsigReservedLen +
                  kLsigSignatureLen == kLsigFooterLen,
              "LSIG footer field sizes must sum to 96");
static_assert(kLsigSignatureOffset + kLsigSignatureLen == kLsigFooterLen,
              "LSIG signature must end at footer end");

// Streaming byte reader called repeatedly with ascending offsets during the
// signed-region hash pass, plus one up-front footer read near imageLen - 96.
// Reads up to wantBytes into out and returns the count read; anything other
// than wantBytes (short read or negative error) fails verification.
using FirmwareByteReader =
    std::function<int(size_t offset, size_t wantBytes, uint8_t* out)>;

// Verify a signed firmware image via a streaming reader.
//   reader     supplies bytes [0 .. imageLen). Footer is read first from
//              offset (imageLen - 96), then the signed region is streamed in
//              ascending blocks.
//   imageLen   total signed image length including the 96-byte footer.
//   outChannel optional. On success, points at a static null-terminated channel
//              buffer; consume it before the next call from another thread (the
//              lamp's verify is serial under the Core 1 state machine).
//   outVersion optional. On success, the packed-semver version field.
//   outDigest  optional 32-byte buffer. On success, the computed SHA-256 of the
//              signed region, so the caller can bind it to an offer-time digest.
// Returns true only if all checks pass; false on any failure, leaving
// out-params unchanged. Failure is silent (the caller decides what to log).
bool verifySignedFirmware(FirmwareByteReader reader, size_t imageLen,
                          const char** outChannel, uint32_t* outVersion,
                          uint8_t* outDigest = nullptr);

// Verify an ed25519 signature over an already-computed 32-byte SHA-256 digest
// against kFirmwarePubkey. This is the offer-time authenticity gate: an OTA
// OFFER carries the signed image's digest + signature, so a receiver rejects an
// unsigned / foreign-key / tampered offer before streaming a byte. Same crypto
// as verifySignedFirmware's final step, minus the image-hash pass.
bool verifyFirmwareDigestSignature(const uint8_t digest[32],
                                   const uint8_t signature[64]);

// Scan a partition FORWARD for the first valid LSIG footer and return the
// running image's total length (footerStart + kLsigFooterLen). A footer is
// valid when its magic is "LSIG" AND signedRegionLen == footerStart (offset
// kLsigSignedLenOffset). The first valid footer is the running image's; a
// stale footer from a smaller predecessor image surviving in the un-erased
// partition tail always sits at a higher offset. Returns false if no valid
// footer is found or on any short/failed read.
//   reader       supplies partition bytes [0 .. partitionLen), ascending.
//   partitionLen full partition size to scan.
//   outLen       on success, footerStart + kLsigFooterLen.
bool discoverSignedImageLength(FirmwareByteReader reader, size_t partitionLen,
                               uint32_t* outLen);

}}  // namespace lamp::firmware
