#pragma once

// Ed25519 public key for verifying signed firmware images during OTA.
//
// REGENERATED by gen_firmware_keys.py — the script rewrites the
// kFirmwarePubkey byte array below from the keypair on disk and leaves
// the rest of this file untouched. The private key lives outside the
// repo with the developer who ran the script; the array below is the
// matching public half that every shipped firmware verifies against.
//
// If you need to rotate the key, run gen_firmware_keys.py; it produces
// a new keypair, writes the public half here, and stores the private
// half at the path printed on stdout.

#include <cstdint>

namespace lamp { namespace firmware {

// 32-byte ed25519 public key, raw form (matches libsodium
// crypto_sign_ed25519_verify_detached's `pk` argument).
constexpr uint8_t kFirmwarePubkey[32] = {
    0x0b, 0x58, 0x84, 0x6d, 0x91, 0xf9, 0x44, 0x7c,
    0x90, 0xcd, 0xa2, 0x26, 0xa4, 0x91, 0xff, 0x33,
    0xd5, 0x5c, 0x0d, 0x14, 0xdb, 0xa9, 0xfe, 0xa4,
    0x89, 0xb0, 0x6e, 0x6c, 0x0d, 0xa6, 0x48, 0xec,
};

}}  // namespace lamp::firmware
