#pragma once
// Host-only. Single source of truth for the per-variant expression catalog
// generator (gen_main.cpp) and the drift-gate test (test_expr_catalog_flash).
// Registers the make-less kExprDescriptorData constants (serializeCatalog never
// emits .make, so make-less bytes == on-device bytes) and renders the committed
// generated/<variant>/expr_catalog.h. Never compiled into firmware.
#include <string>
#include <vector>

#include "expressions/breathing/breathing_expression.hpp"
#include "expressions/glitchy/glitchy_expression.hpp"
#include "expressions/pulse/pulse_expression.hpp"
#include "expressions/shifty/shifty_expression.hpp"
#include "expressions/shimmer/shimmer_expression.hpp"
#include "expressions/spotty/spotty_expression.hpp"

#include "../../src/expressions/expression_registry.cpp"

namespace lamp::catalog_gen {

struct VariantSpec {
  const char* name;
  std::vector<const ExpressionDescriptor*> subset;
};

// The editable-expression subset each variant registers at runtime
// (Lamp::registerExpressions and the variant overrides). Keep in step with
// those; the drift test guards the committed bytes, not this list vs runtime.
inline std::vector<VariantSpec> variantSpecs() {
  const std::vector<const ExpressionDescriptor*> base6 = {
      &kGlitchyDescriptorData, &kPulseDescriptorData, &kBreathingDescriptorData,
      &kShiftyDescriptorData,  &kSpottyDescriptorData, &kShimmerDescriptorData};
  return {
      {"standard", base6},
      {"staff", base6},
      {"lioness", base6},
      {"loaf", base6},
      {"snafu",
       {&kGlitchyDescriptorData, &kPulseDescriptorData, &kSpottyDescriptorData,
        &kShimmerDescriptorData}},
  };
}

inline std::string buildCatalog(const VariantSpec& v) {
  ExpressionRegistry reg;
  for (const auto* d : v.subset) reg.add(*d);
  return reg.serializeCatalog();
}

inline std::string emitHeader(const VariantSpec& v) {
  const std::string json = buildCatalog(v);
  std::string lit;
  lit.reserve(json.size() + 16);
  for (char c : json) {
    if (c == '\\' || c == '"') lit += '\\';
    lit += c;
  }
  std::string out;
  out += "#pragma once\n";
  out += "// Generated by npm run catalog:gen (scripts/gen_expr_catalog.py). Do not edit.\n";
  out += "// Expression catalog for the ";
  out += v.name;
  out += " build, held in .rodata (flash), served by reference.\n";
  out += "#include <cstddef>\n\n";
  out += "namespace lamp {\n\n";
  out += "inline constexpr char kExprCatalog[] = \"";
  out += lit;
  out += "\";\n";
  out += "inline constexpr size_t kExprCatalogLen = sizeof(kExprCatalog) - 1;\n\n";
  out += "}  // namespace lamp\n";
  return out;
}

}  // namespace lamp::catalog_gen
