#pragma once
// Host-only. Single source of truth for the per-variant expression catalog
// generator (gen_main.cpp) and the drift-gate test (test_expr_catalog_flash).
// Registers the make-less kExprDescriptorData constants (serializeCatalog never
// emits .make, so make-less bytes == on-device bytes) and renders the committed
// generated/<variant>/expr_catalog.h. Never compiled into firmware.
#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>

#include "expressions/bloom/bloom_expression.hpp"
#include "expressions/breathing/breathing_expression.hpp"
#include "expressions/expr_variant_sets.hpp"
#include "expressions/glitchy/glitchy_expression.hpp"
#include "expressions/pulse/pulse_expression.hpp"
#include "expressions/shifty/shifty_expression.hpp"
#include "expressions/shimmer/shimmer_expression.hpp"
#include "expressions/spotty/spotty_expression.hpp"

#include "../../src/expressions/expression_registry.cpp"

namespace lamp::catalog_gen {

struct VariantSpec {
  const char* name;
  std::vector<const ExpressionDescriptor*> subset;
};

// The editable-expression subset each variant registers at runtime, expanded
// from the SAME per-variant X-macro the runtime registration uses
// (expressions/expr_variant_sets.hpp), so the generated catalog cannot drift
// from what the device serves.
inline std::vector<VariantSpec> variantSpecs() {
#define X(N) &k##N##DescriptorData,
  const std::vector<const ExpressionDescriptor*> base = {LAMPOS_BASE_EXPRESSIONS(X)};
  const std::vector<const ExpressionDescriptor*> staff = {LAMPOS_STAFF_EXPRESSIONS(X)};
  const std::vector<const ExpressionDescriptor*> snafu = {LAMPOS_SNAFU_EXPRESSIONS(X)};
#undef X
  return {
      {"standard", base},
      {"staff", staff},
      {"lioness", base},
      {"loaf", base},
      {"snafu", snafu},
  };
}

inline std::string buildCatalog(const VariantSpec& v) {
  ExpressionRegistry reg;
  for (const auto* d : v.subset) reg.add(*d);
  return reg.serializeCatalog();
}

inline uint32_t fnv1a32(const std::string& bytes) {
  uint32_t h = 2166136261u;
  for (unsigned char c : bytes) {
    h ^= c;
    h *= 16777619u;
  }
  return h;
}

inline std::string emitHeader(const VariantSpec& v) {
  const std::string json = buildCatalog(v);
  std::string lit;
  lit.reserve(json.size() + 16);
  for (char c : json) {
    if (c == '\\' || c == '"') lit += '\\';
    lit += c;
  }
  std::string out;
  out += "#pragma once\n";
  out += "// Generated by npm run catalog:gen (scripts/gen_expr_catalog.py). Do not edit.\n";
  out += "// Expression catalog for the ";
  out += v.name;
  out += " build, held in .rodata (flash), served by reference.\n";
  out += "#include <cstddef>\n";
  out += "#include <cstdint>\n\n";
  out += "namespace lamp {\n\n";
  out += "inline constexpr char kExprCatalog[] = \"";
  out += lit;
  out += "\";\n";
  out += "inline constexpr size_t kExprCatalogLen = sizeof(kExprCatalog) - 1;\n";
  char hashLit[24];
  std::snprintf(hashLit, sizeof(hashLit), "0x%08xu", fnv1a32(json));
  out += "inline constexpr uint32_t kExprCatalogHash = ";
  out += hashLit;
  out += ";\n\n";
  out += "}  // namespace lamp\n";
  return out;
}

}  // namespace lamp::catalog_gen
