#!/usr/bin/env python3
"""Generate the ed25519 signing keypair for lamp firmware OTA.

Produces:
  - ~/.lamp-os-firmware-key.bin (32-byte raw private seed). Held by the
    developer; NEVER committed. Lose this and the entire deployed fleet
    can no longer accept new OTA pushes (their kFirmwarePubkey is baked
    into the boot firmware; only USB re-flash with a fresh pubkey
    recovers).
  - software/lamp-os/src/components/firmware/firmware_pubkey.h — the matching
    public key as a 32-byte C++ constexpr array. This file IS committed;
    every rotation re-runs the generator and bumps the fleet.

The header is regenerated by overwriting ONLY the 32 byte values inside
the `kFirmwarePubkey` literal — the #pragma once / includes / namespace
block / closing braces are preserved verbatim across runs. Round-trip
safe: running the script twice produces well-formed output both times.

Crypto backend: prefers PyNaCl (libsodium bindings) — matches the
firmware's libsodium verifier exactly. Falls back to the `cryptography`
package if PyNaCl is unavailable.

Usage:
  python3 scripts/gen_firmware_keys.py                       # refuse to overwrite
  python3 scripts/gen_firmware_keys.py --force               # rotate the fleet key
  python3 scripts/gen_firmware_keys.py --rewrite-pubkey-only # derive pubkey from
                                                             # existing private key
                                                             # and rewrite header
                                                             # (preserves the key
                                                             # that signed any
                                                             # existing firmware)

Exit codes:
  0 — keys generated and self-test passed
  1 — refuse to overwrite (no --force) OR self-test failed OR header
      could not be rewritten
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

# Resolved relative to this script's location so it works regardless of
# the caller's cwd (PIO scripts hook from elsewhere).
SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
PUBKEY_HEADER = REPO_ROOT / "software" / "lamp-os" / "src" / "components" / "firmware" / "firmware_pubkey.h"
PRIVATE_KEY_PATH = Path.home() / ".lamp-os-firmware-key.bin"


def _generate_keypair() -> tuple[bytes, bytes]:
    """Return (private_seed_32, public_key_32). Tries PyNaCl first."""
    try:
        from nacl.signing import SigningKey  # type: ignore

        sk = SigningKey.generate()
        priv = bytes(sk)  # 32-byte seed
        pub = bytes(sk.verify_key)
        return priv, pub
    except ImportError:
        pass

    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import (
            Ed25519PrivateKey,
        )
        from cryptography.hazmat.primitives import serialization

        sk = Ed25519PrivateKey.generate()
        priv = sk.private_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PrivateFormat.Raw,
            encryption_algorithm=serialization.NoEncryption(),
        )
        pub = sk.public_key().public_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PublicFormat.Raw,
        )
        return priv, pub
    except ImportError:
        print(
            "[gen_firmware_keys] FATAL: neither PyNaCl nor `cryptography` is "
            "installed. Try: pip install pynacl  OR  pip install cryptography",
            file=sys.stderr,
        )
        sys.exit(1)


def _derive_pubkey_from_private(priv: bytes) -> bytes:
    """Compute the 32-byte ed25519 public key for `priv` (32-byte seed)."""
    try:
        from nacl.signing import SigningKey  # type: ignore

        return bytes(SigningKey(priv).verify_key)
    except ImportError:
        pass

    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import (
            Ed25519PrivateKey,
        )
        from cryptography.hazmat.primitives import serialization

        sk = Ed25519PrivateKey.from_private_bytes(priv)
        return sk.public_key().public_bytes(
            encoding=serialization.Encoding.Raw,
            format=serialization.PublicFormat.Raw,
        )
    except ImportError:
        print(
            "[gen_firmware_keys] FATAL: neither PyNaCl nor `cryptography` is "
            "installed. Try: pip install pynacl  OR  pip install cryptography",
            file=sys.stderr,
        )
        sys.exit(1)


def _sign_and_verify(priv: bytes, pub: bytes) -> bool:
    """Round-trip a known message. Returns True iff verify passes.

    Uses the same backend that produced the keypair; both PyNaCl and
    cryptography mirror libsodium semantics so this is representative of
    the firmware's runtime verification path.
    """
    msg = b"lamp-os firmware key self-test"
    try:
        from nacl.signing import SigningKey, VerifyKey  # type: ignore

        sig = SigningKey(priv).sign(msg).signature
        VerifyKey(pub).verify(msg, sig)
        return True
    except ImportError:
        pass

    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import (
            Ed25519PrivateKey,
            Ed25519PublicKey,
        )
        from cryptography.exceptions import InvalidSignature

        sk = Ed25519PrivateKey.from_private_bytes(priv)
        sig = sk.sign(msg)
        try:
            Ed25519PublicKey.from_public_bytes(pub).verify(sig, msg)
            return True
        except InvalidSignature:
            return False
    except ImportError:
        return False


# Matches the byte-array literal inside the existing pubkey header. The
# header guarantees the same `constexpr uint8_t kFirmwarePubkey[32] = {`
# preamble + closing `};`; we replace only the bytes in between.
_PUBKEY_LITERAL_RE = re.compile(
    r"(constexpr\s+uint8_t\s+kFirmwarePubkey\s*\[\s*32\s*\]\s*=\s*\{)"
    r"[^}]*"
    r"(\};)",
    re.DOTALL,
)


def _format_pubkey_literal(pub: bytes) -> str:
    """Render the 32 bytes as 4 rows of 8 hex bytes for readable diffs."""
    if len(pub) != 32:
        raise ValueError(f"expected 32-byte pubkey, got {len(pub)}")
    rows = []
    for row in range(4):
        chunk = pub[row * 8 : (row + 1) * 8]
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n" + "\n".join(rows) + "\n"


def _rewrite_pubkey_header(path: Path, pub: bytes) -> None:
    """Overwrite ONLY the array bytes inside the existing header file."""
    if not path.exists():
        print(f"[gen_firmware_keys] FATAL: pubkey header not found at {path}", file=sys.stderr)
        sys.exit(1)
    original = path.read_text()
    new_literal_body = _format_pubkey_literal(pub)
    replaced, count = _PUBKEY_LITERAL_RE.subn(
        lambda m: m.group(1) + new_literal_body + m.group(2),
        original,
        count=1,
    )
    if count != 1:
        print(
            "[gen_firmware_keys] FATAL: could not locate kFirmwarePubkey[32] "
            f"literal in {path}. Re-create the file from the committed stub.",
            file=sys.stderr,
        )
        sys.exit(1)
    path.write_text(replaced)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite an existing private key (rotates the fleet trust root)",
    )
    parser.add_argument(
        "--rewrite-pubkey-only",
        action="store_true",
        help="derive the pubkey from the existing private key and rewrite "
             "ONLY the header; do not touch the private key. Use when the "
             "header drifted out of sync (e.g. stub committed by mistake).",
    )
    args = parser.parse_args(argv)

    if args.rewrite_pubkey_only:
        if not PRIVATE_KEY_PATH.exists():
            print(
                f"[gen_firmware_keys] FATAL: --rewrite-pubkey-only needs an "
                f"existing private key at {PRIVATE_KEY_PATH}, but none was "
                f"found. Run without --rewrite-pubkey-only to create one.",
                file=sys.stderr,
            )
            return 1
        priv = PRIVATE_KEY_PATH.read_bytes()
        if len(priv) != 32:
            print(
                f"[gen_firmware_keys] FATAL: private key at {PRIVATE_KEY_PATH} "
                f"is {len(priv)} bytes, expected 32.",
                file=sys.stderr,
            )
            return 1
        pub = _derive_pubkey_from_private(priv)
        if not _sign_and_verify(priv, pub):
            print(
                "[gen_firmware_keys] FATAL: derived pubkey fails sign+verify "
                "self-test against the existing private key.",
                file=sys.stderr,
            )
            return 1
        _rewrite_pubkey_header(PUBKEY_HEADER, pub)
        print("OK (pubkey-only)")
        print(f"  private key:  {PRIVATE_KEY_PATH}  (unchanged)")
        print(f"  public key:   {PUBKEY_HEADER}")
        print(f"  pubkey hex:   {pub.hex()}")
        return 0

    if PRIVATE_KEY_PATH.exists() and not args.force:
        print(
            f"[gen_firmware_keys] REFUSING to overwrite existing private key at\n"
            f"    {PRIVATE_KEY_PATH}\n"
            f"\n"
            f"  Rotating the key means every lamp in the fleet will REJECT\n"
            f"  every future OTA push until each one is USB-re-flashed with\n"
            f"  the new pubkey baked in. If that's intentional, re-run with\n"
            f"  --force.\n",
            file=sys.stderr,
        )
        return 1

    priv, pub = _generate_keypair()

    if not _sign_and_verify(priv, pub):
        print(
            "[gen_firmware_keys] FATAL: sign+verify self-test failed. "
            "The generated keypair is corrupt; not writing any files.",
            file=sys.stderr,
        )
        return 1

    # Write private key with restrictive permissions (owner read-only). The
    # mode mask is applied AFTER the write, so a transient world-read
    # window of ~1 syscall exists; acceptable since this is a dev-machine
    # operation, not a production secret store.
    PRIVATE_KEY_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(PRIVATE_KEY_PATH, "wb") as fh:
        fh.write(priv)
    try:
        os.chmod(PRIVATE_KEY_PATH, 0o600)
    except OSError:
        # Best-effort on non-POSIX filesystems; the file is still owner-private
        # on macOS/Linux where this script runs.
        pass

    _rewrite_pubkey_header(PUBKEY_HEADER, pub)

    print("OK")
    print(f"  private key:  {PRIVATE_KEY_PATH}  ({len(priv)} bytes, mode 0600)")
    print(f"  public key:   {PUBKEY_HEADER}")
    print(f"  pubkey hex:   {pub.hex()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
