/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "aurora_notifications.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(aurora_Any, aurora_Any, 2)


PB_BIND(aurora_NotificationEnvelope, aurora_NotificationEnvelope, 2)


PB_BIND(aurora_InstanceInfo, aurora_InstanceInfo, AUTO)


PB_BIND(aurora_NotificationSubscription, aurora_NotificationSubscription, AUTO)


PB_BIND(aurora_NotificationSubscriptionRequest, aurora_NotificationSubscriptionRequest, 2)


PB_BIND(aurora_ZonePaletteState, aurora_ZonePaletteState, AUTO)


PB_BIND(aurora_PaletteState, aurora_PaletteState, 2)


PB_BIND(aurora_PatternState, aurora_PatternState, AUTO)







