/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AURORA_AURORA_NOTIFICATIONS_PB_H_INCLUDED
#define PB_AURORA_AURORA_NOTIFICATIONS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _aurora_NotificationType {
    aurora_NotificationType_INSTANCE_INFO = 1,
    aurora_NotificationType_GLOBAL_STATE = 5,
    aurora_NotificationType_PALETTE_STATE = 6,
    aurora_NotificationType_CACHE_INVALIDATE = 13,
    aurora_NotificationType_LIVE_DATA_SUBSCRIPTION = 20,
    aurora_NotificationType_PATTERN_STATE = 33
} aurora_NotificationType;

typedef enum _aurora_SubscriptionAction {
    aurora_SubscriptionAction_SUBSCRIBE = 1,
    aurora_SubscriptionAction_UNSUBSCRIBE = 2,
    aurora_SubscriptionAction_REPLACE = 3
} aurora_SubscriptionAction;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(2048) aurora_Any_value_t;
/* Local copy of google.protobuf.Any (identical wire layout). */
typedef struct _aurora_Any {
    bool has_type_url;
    char type_url[128];
    bool has_value;
    aurora_Any_value_t value;
} aurora_Any;

typedef struct _aurora_NotificationEnvelope {
    bool has_type;
    aurora_NotificationType type;
    bool has_msg;
    aurora_Any msg;
    bool has_instance_id;
    char instance_id[64];
} aurora_NotificationEnvelope;

typedef struct _aurora_InstanceInfo {
    bool has_instance_id;
    char instance_id[64];
} aurora_InstanceInfo;

typedef struct _aurora_NotificationSubscription {
    bool has_subscription_id;
    char subscription_id[48];
    bool has_type;
    aurora_NotificationType type;
    bool has_action;
    aurora_SubscriptionAction action; /* filter (field 4, Any) intentionally omitted: we send no filters. */
} aurora_NotificationSubscription;

typedef struct _aurora_NotificationSubscriptionRequest {
    pb_size_t subscriptions_count;
    aurora_NotificationSubscription subscriptions[24];
    bool has_replace_all;
    bool replace_all;
} aurora_NotificationSubscriptionRequest;

/* zone/enum fields declared as int32 to avoid importing pattern.proto. */
typedef struct _aurora_ZonePaletteState {
    bool has_zone;
    int32_t zone;
    bool has_active_color_palette_id;
    char active_color_palette_id[48];
    bool has_active_fx_snapshot_id;
    char active_fx_snapshot_id[48];
} aurora_ZonePaletteState;

typedef struct _aurora_PaletteState {
    pb_size_t states_count;
    aurora_ZonePaletteState states[16];
    bool has_fx_snapshot_id_preview;
    char fx_snapshot_id_preview[48];
} aurora_PaletteState;

/* Trimmed: only scalar fields we surface; nested params/transitions skipped. */
typedef struct _aurora_PatternState {
    bool has_mode;
    int32_t mode;
    bool has_status;
    int32_t status;
    bool has_play_index;
    int32_t play_index;
    bool has_show_id;
    char show_id[48];
    bool has_preview_enabled;
    bool preview_enabled;
} aurora_PatternState;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _aurora_NotificationType_MIN aurora_NotificationType_INSTANCE_INFO
#define _aurora_NotificationType_MAX aurora_NotificationType_PATTERN_STATE
#define _aurora_NotificationType_ARRAYSIZE ((aurora_NotificationType)(aurora_NotificationType_PATTERN_STATE+1))

#define _aurora_SubscriptionAction_MIN aurora_SubscriptionAction_SUBSCRIBE
#define _aurora_SubscriptionAction_MAX aurora_SubscriptionAction_REPLACE
#define _aurora_SubscriptionAction_ARRAYSIZE ((aurora_SubscriptionAction)(aurora_SubscriptionAction_REPLACE+1))


#define aurora_NotificationEnvelope_type_ENUMTYPE aurora_NotificationType


#define aurora_NotificationSubscription_type_ENUMTYPE aurora_NotificationType
#define aurora_NotificationSubscription_action_ENUMTYPE aurora_SubscriptionAction






/* Initializer values for message structs */
#define aurora_Any_init_default                  {false, "", false, {0, {0}}}
#define aurora_NotificationEnvelope_init_default {false, _aurora_NotificationType_MIN, false, aurora_Any_init_default, false, ""}
#define aurora_InstanceInfo_init_default         {false, ""}
#define aurora_NotificationSubscription_init_default {false, "", false, _aurora_NotificationType_MIN, false, _aurora_SubscriptionAction_MIN}
#define aurora_NotificationSubscriptionRequest_init_default {0, {aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default, aurora_NotificationSubscription_init_default}, false, 0}
#define aurora_ZonePaletteState_init_default     {false, 0, false, "", false, ""}
#define aurora_PaletteState_init_default         {0, {aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default, aurora_ZonePaletteState_init_default}, false, ""}
#define aurora_PatternState_init_default         {false, 0, false, 0, false, 0, false, "", false, 0}
#define aurora_Any_init_zero                     {false, "", false, {0, {0}}}
#define aurora_NotificationEnvelope_init_zero    {false, _aurora_NotificationType_MIN, false, aurora_Any_init_zero, false, ""}
#define aurora_InstanceInfo_init_zero            {false, ""}
#define aurora_NotificationSubscription_init_zero {false, "", false, _aurora_NotificationType_MIN, false, _aurora_SubscriptionAction_MIN}
#define aurora_NotificationSubscriptionRequest_init_zero {0, {aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero, aurora_NotificationSubscription_init_zero}, false, 0}
#define aurora_ZonePaletteState_init_zero        {false, 0, false, "", false, ""}
#define aurora_PaletteState_init_zero            {0, {aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero, aurora_ZonePaletteState_init_zero}, false, ""}
#define aurora_PatternState_init_zero            {false, 0, false, 0, false, 0, false, "", false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define aurora_Any_type_url_tag                  1
#define aurora_Any_value_tag                     2
#define aurora_NotificationEnvelope_type_tag     1
#define aurora_NotificationEnvelope_msg_tag      2
#define aurora_NotificationEnvelope_instance_id_tag 3
#define aurora_InstanceInfo_instance_id_tag      1
#define aurora_NotificationSubscription_subscription_id_tag 1
#define aurora_NotificationSubscription_type_tag 2
#define aurora_NotificationSubscription_action_tag 3
#define aurora_NotificationSubscriptionRequest_subscriptions_tag 1
#define aurora_NotificationSubscriptionRequest_replace_all_tag 2
#define aurora_ZonePaletteState_zone_tag         1
#define aurora_ZonePaletteState_active_color_palette_id_tag 2
#define aurora_ZonePaletteState_active_fx_snapshot_id_tag 3
#define aurora_PaletteState_states_tag           1
#define aurora_PaletteState_fx_snapshot_id_preview_tag 2
#define aurora_PatternState_mode_tag             1
#define aurora_PatternState_status_tag           2
#define aurora_PatternState_play_index_tag       8
#define aurora_PatternState_show_id_tag          9
#define aurora_PatternState_preview_enabled_tag  11

/* Struct field encoding specification for nanopb */
#define aurora_Any_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   type_url,          1) \
X(a, STATIC,   OPTIONAL, BYTES,    value,             2)
#define aurora_Any_CALLBACK NULL
#define aurora_Any_DEFAULT NULL

#define aurora_NotificationEnvelope_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  msg,               2) \
X(a, STATIC,   OPTIONAL, STRING,   instance_id,       3)
#define aurora_NotificationEnvelope_CALLBACK NULL
#define aurora_NotificationEnvelope_DEFAULT (const pb_byte_t*)"\x08\x01\x00"
#define aurora_NotificationEnvelope_msg_MSGTYPE aurora_Any

#define aurora_InstanceInfo_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   instance_id,       1)
#define aurora_InstanceInfo_CALLBACK NULL
#define aurora_InstanceInfo_DEFAULT NULL

#define aurora_NotificationSubscription_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   subscription_id,   1) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              2) \
X(a, STATIC,   OPTIONAL, UENUM,    action,            3)
#define aurora_NotificationSubscription_CALLBACK NULL
#define aurora_NotificationSubscription_DEFAULT (const pb_byte_t*)"\x10\x01\x18\x01\x00"

#define aurora_NotificationSubscriptionRequest_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  subscriptions,     1) \
X(a, STATIC,   OPTIONAL, BOOL,     replace_all,       2)
#define aurora_NotificationSubscriptionRequest_CALLBACK NULL
#define aurora_NotificationSubscriptionRequest_DEFAULT NULL
#define aurora_NotificationSubscriptionRequest_subscriptions_MSGTYPE aurora_NotificationSubscription

#define aurora_ZonePaletteState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    zone,              1) \
X(a, STATIC,   OPTIONAL, STRING,   active_color_palette_id,   2) \
X(a, STATIC,   OPTIONAL, STRING,   active_fx_snapshot_id,   3)
#define aurora_ZonePaletteState_CALLBACK NULL
#define aurora_ZonePaletteState_DEFAULT NULL

#define aurora_PaletteState_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  states,            1) \
X(a, STATIC,   OPTIONAL, STRING,   fx_snapshot_id_preview,   2)
#define aurora_PaletteState_CALLBACK NULL
#define aurora_PaletteState_DEFAULT NULL
#define aurora_PaletteState_states_MSGTYPE aurora_ZonePaletteState

#define aurora_PatternState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    mode,              1) \
X(a, STATIC,   OPTIONAL, INT32,    status,            2) \
X(a, STATIC,   OPTIONAL, INT32,    play_index,        8) \
X(a, STATIC,   OPTIONAL, STRING,   show_id,           9) \
X(a, STATIC,   OPTIONAL, BOOL,     preview_enabled,  11)
#define aurora_PatternState_CALLBACK NULL
#define aurora_PatternState_DEFAULT NULL

extern const pb_msgdesc_t aurora_Any_msg;
extern const pb_msgdesc_t aurora_NotificationEnvelope_msg;
extern const pb_msgdesc_t aurora_InstanceInfo_msg;
extern const pb_msgdesc_t aurora_NotificationSubscription_msg;
extern const pb_msgdesc_t aurora_NotificationSubscriptionRequest_msg;
extern const pb_msgdesc_t aurora_ZonePaletteState_msg;
extern const pb_msgdesc_t aurora_PaletteState_msg;
extern const pb_msgdesc_t aurora_PatternState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define aurora_Any_fields &aurora_Any_msg
#define aurora_NotificationEnvelope_fields &aurora_NotificationEnvelope_msg
#define aurora_InstanceInfo_fields &aurora_InstanceInfo_msg
#define aurora_NotificationSubscription_fields &aurora_NotificationSubscription_msg
#define aurora_NotificationSubscriptionRequest_fields &aurora_NotificationSubscriptionRequest_msg
#define aurora_ZonePaletteState_fields &aurora_ZonePaletteState_msg
#define aurora_PaletteState_fields &aurora_PaletteState_msg
#define aurora_PatternState_fields &aurora_PatternState_msg

/* Maximum encoded size of messages (where known) */
#define AURORA_AURORA_NOTIFICATIONS_PB_H_MAX_SIZE aurora_NotificationEnvelope_size
#define aurora_Any_size                          2181
#define aurora_InstanceInfo_size                 65
#define aurora_NotificationEnvelope_size         2251
#define aurora_NotificationSubscriptionRequest_size 1322
#define aurora_NotificationSubscription_size     53
#define aurora_PaletteState_size                 1825
#define aurora_PatternState_size                 84
#define aurora_ZonePaletteState_size             109

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
